language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - cd kboard && ./manage.py runserver &
  - sleep 3 # wait to server run
# command to run tests
script: cd kboard && python functional_test.py
